apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: uscornie-db
spec:
  instances: {{ .Values.postgres.instances }}
  storage:
    size: {{ .Values.postgres.storageSize }}
  bootstrap:
    initdb:
      database: uscornie
      owner: app
