image:
  repository: ghcr.io/khoanguyenn/uscornie-backend
  tag: 0.1.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

postgres:
  instances: 1
  storageSize: 5Gi

# These secrets must be created manually in the uscornie namespace:
# kubectl -n uscornie create secret generic uscornie-secrets \
#   --from-literal=GOOGLE_CLIENT_ID=xxx \
#   --from-literal=GOOGLE_CLIENT_SECRET=xxx \
#   --from-literal=JWT_SECRET=xxx
