name: Tag Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write

jobs:
  tag-version:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'release-preview'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Changie
        uses: miniscruff/changie-action@v2
        with:
          version: latest

      - name: Get latest version
        id: changie_version
        run: |
          VERSION=$(changie latest)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Git Tag
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.USCORNIE_RELEASE_BOT_TOKEN }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ steps.changie_version.outputs.version }}',
              sha: context.sha
            })
